baseURL = "https://koa.im/"
languageCode = "zh-cn"
title = "Kouga's Blog"
# theme = "uBlogger"
theme = [ "m10c"]
paginate = 10


pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "dracula"
pygmentsUseClasses = true

[params]
  # uBlogger theme version
  version = "2.0.X"
  author = "Whale Mo"
  description = "A simple blog for some idea or fun."
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ncwhale"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/Kouga_"

[params.search]
  enable = true
  # type of search engine ("lunr", "algolia")
  type = "lunr"
  # max index length of the chunked content
  contentLength = 1200
  # placeholder of the search bar
  placeholder = ""
  # uBlogger NEW | 0.2.1 max number of results length
  maxResultLength = 10
  # uBlogger NEW | 0.2.3 snippet length of the result
  snippetLength = 30
  # uBlogger NEW | 0.2.1 HTML tag name of the highlight part in results
  highlightTag = "em"
  # uBlogger NEW | 0.2.4 whether to use the absolute URL based on the baseURL in search index
  absoluteURL = false

    [params.page.library]
      [params.page.library.css]
        syntax = "syntax.css"
[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Blog"
    url = "/blog/"
    # title will be shown when you hover on this menu link
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  # [markup.highlight]
  #   noClasses = false
  #   # anchorLineNos = false
  #   codeFences = true
  #   guessSyntax = true
  #   # hl_Lines = ""
  #   # lineAnchors = ""
  #   lineNoStart = 1
  #   lineNos = true
  #   lineNumbersInTable = true
  #   style = "dracula"
  #   tabWidth = 2

[outputs]
  home = ["HTML", "RSS", "JSON"]